### ISSUE TITLE
검색어변수 제거 기능이 동작하지 않습니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-force-rewrite#2]
저희가 사용하는 XE 말고 라이믹스 사용자분한테도 같은 문의가 들어왔네요.
그리고 XE타운에서 테스트를 해보면 클릭시 짧은주소로 이동은 하지만 하단의 목록은 검색어 반영이 안된 목록으로 노출이 됩니다.

**Comment by wookho** [comment]
PC에서 사용하는 스킨의 문제라면 닫아주세요.
https://xetown.com/qna/1070719

**Comment by kijin** [comment]
`_filter`와 같은 무의미한 변수도 자동으로 제거하도록 개선해 보겠습니다.

**Comment by wookho** [comment]
@kijin 그런데 문제는 어디서부터 출발했는지 모르지만 지금 공개된 꽤 많은 스킨이 이 것을 사용하고 있는게 문제네요. 저희는 일단 제거해서 문제는 없습니다만 지속적으로 문의가 들어오는 상황이라 애드온에서 처리하는 것도 방법일 것 같습니다.

**Comment by wookho** [comment]
@kijin 2-40 글자를 걸러내려고 사용하는 것 같긴 합니다.

**Comment by kijin** [comment]
수정되었습니다. 28a158b
