### ISSUE TITLE
푸시앱에서 이상동작이 발생합니다. 

### ISSUE THREAD

**Issue by wookho** [poesis/xe-force-rewrite#3]
글 읽는 화면에서 PC화면 보기가 필요할때 링크를 누르면 짧은주소로 리디렉트 되어버려 PC보기로 진입이 불가능합니다.

같은 게시판이라도 list 상태에서는 Pc보기로 진입이 가능하나
글읽는 곳에서 해당 요청을 하면 애드온이 동작하여 진입을 할 수가 없습니다.

저희사이트에서는 약간 크리티컬한 문제이네요.

**Comment by kijin** [comment]
혹시 PC화면보기 링크 구조가 어떻게 되는지 알 수 있을까요?

https://github.com/poesis/xe-force-rewrite/blob/master/force_rewrite.addon.php#L166-L170
이 부분을 삭제 또는 주석처리한 경우 차이가 있나요?

**Comment by wookho** [comment]
@kijin 웹을 그대로 띄우기 때문에 링크는 같습니다. 
말씀 하신 부분 주석 처리 하니 해당 증상은 없어졌습니다.

**Comment by kijin** [comment]
Fixed in 2.2.0

`l`, `m` 등의 변수를 제거하는 기능을 별도의 옵션으로 분리했으며, OFF로 해두는 것을 권장합니다. 사실 이런 변수를 사용하면 페이지 내용이 완전히 달라질 수도 있기 때문에, 별도로 색인되더라도 상관없을 것 같네요.
